--- 
after_success: 
  - "ssh deimo@39.104.92.227 'cd /home/deimo/front/gnu-dlpu-serverside && git pull'"
before_install: 
  - "openssl aes-256-cbc -K $encrypted_46ebf854063c_key -iv $encrypted_46ebf854063c_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d"
  - "chmod 600 ~/.ssh/id_rsa"
  - "echo -e \"Host 39.104.92.227\\n\\tStrictHostKeyChecking no\\n\" >> ~/.ssh/config"

